name       : gnome-terminal
version    : 3.44.1
release    : 53
source     :
    - https://download.gnome.org/sources/gnome-terminal/3.44/gnome-terminal-3.44.1.tar.xz : fb6f20ee1ff231a9aaedab13d5dc6e5a64c955711224848b790086e88959d37b
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Terminal Emulator
description: |
    GNOME Terminal Emulator
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libpcre2-8)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
setup      : |
    %apply_patches
    %meson_configure -Dsearch_provider=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
