name        : gnome-terminal
version     : 3.16.2
release     : 15
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-terminal/3.16/gnome-terminal-3.16.2.tar.xz : 9df7bab7bfd15ca9a3c60612e425baaf5c8b32ba181619f740b7129a0768f4e0
license     : GPL-2.0+
summary     : GNOME Terminal Emulator
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnautilus-extension)
    - appdata-tools
    - desktop-file-utils
    - itstool
    - vala
description : |
    GNOME Terminal Emulator
setup      : |
    %patch -p1 < $pkgfiles/restore-transparency.patch
    %configure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
