name       : gnome-terminal
version    : 3.38.1
release    : 44
source     :
    - https://download.gnome.org/sources/gnome-terminal/3.38/gnome-terminal-3.38.1.tar.xz : d998d4824f38847fdd74bad6b5f09cc8e11b9de8e2a284a439af290714ddf3d1
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Terminal Emulator
description: |
    GNOME Terminal Emulator
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libpcre2-8)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - appdata-tools
    - desktop-file-utils
    - gnome-common
    - itstool
    - yelp-tools
setup      : |
    %apply_patches
    %reconfigure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
