name       : gnome-terminal
version    : 3.24.0
release    : 29
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-terminal/3.24/gnome-terminal-3.24.0.tar.xz : 77698e5c8dec545737c98befc806ae34884cf2be5eb6743332895315f811fb17
license    : GPL-2.0+
summary    : GNOME Terminal Emulator
component  : desktop.gnome
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - appdata-tools
    - desktop-file-utils
    - itstool
    - vala
    - gnome-common
    - yelp-tools
description: |
    GNOME Terminal Emulator
setup      : |
    # Borrowed from Fedora, thanks guys :]
    %patch -p1 < $pkgfiles/gnome-terminal-notify-open-title-transparency.patch
    %patch -p1 < $pkgfiles/0001-build-Don-t-treat-warnings-as-errors.patch
    # Solus
    %patch -p1 < $pkgfiles/0001-Restore-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Default-to-the-dark-theme.patch
    autoreconf -vfi
    %configure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
