name       : gnome-terminal
version    : 3.20.2
release    : 27
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-terminal/3.20/gnome-terminal-3.20.2.tar.xz : f5383060730f1de70af35e917f82d5b6a14d963ad9cfd6a0e705f90011645a23
license    : GPL-2.0+
summary    : GNOME Terminal Emulator
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(yelp-xsl)
    - appdata-tools
    - desktop-file-utils
    - itstool
    - vala
    - gnome-common
    - yelp-tools
description: |
    GNOME Terminal Emulator
setup      : |
    # Borrowed from Fedora, thanks guys :]
    %patch -p1 < $pkgfiles/gnome-terminal-transparency-notify.patch
    %patch -p1 < $pkgfiles/0001-build-Don-t-treat-warnings-as-errors.patch
    # Solus
    %patch -p1 < $pkgfiles/0001-Restore-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Default-to-the-dark-theme.patch
    autoreconf -vfi
    %configure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
