name        : gnome-terminal
version     : 3.18.2
release     : 20
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-terminal/3.18/gnome-terminal-3.18.2.tar.xz : 5e35c0fa1395258bab83952cfabe4c1828b8655bcd761f8faed70b452bd89efa
license     : GPL-2.0+
summary     : GNOME Terminal Emulator
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnautilus-extension)
    - appdata-tools
    - desktop-file-utils
    - itstool
    - vala
    - gnome-common
description : |
    GNOME Terminal Emulator
setup      : |
    %configure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
