name        : gnome-terminal
version     : 3.18.3
release     : 21
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-terminal/3.18/gnome-terminal-3.18.3.tar.xz : 14c2fce1c6a80a3fb0cc8666d7752228adcb60d199634ab69150de32e3c17d56
license     : GPL-2.0+
summary     : GNOME Terminal Emulator
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnautilus-extension)
    - appdata-tools
    - desktop-file-utils
    - itstool
    - vala
    - gnome-common
description : |
    GNOME Terminal Emulator
setup      : |
    %configure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
