name       : gnome-terminal
version    : 3.42.1
release    : 52
source     :
    - https://download.gnome.org/sources/gnome-terminal/3.42/gnome-terminal-3.42.1.tar.xz : c319b1405501b8c7693e616f48eced41695d2e786148ca5f9e27bc7d98f4aeb1
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Terminal Emulator
description: |
    GNOME Terminal Emulator
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libpcre2-8)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
setup      : |
    %apply_patches
    %meson_configure -Dsearch_provider=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
