name       : gnome-terminal
version    : 3.28.1
release    : 34
source     :
    - https://download.gnome.org/sources/gnome-terminal/3.28/gnome-terminal-3.28.1.tar.xz : f7a6a0189a0b0fbf7845d092e5444fc6303225c2d9ef87bfaae3f80845801cc3
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Terminal Emulator
description: |
    GNOME Terminal Emulator
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - appdata-tools
    - desktop-file-utils
    - gnome-common
    - itstool
    - yelp-tools-devel
setup      : |
    # Borrowed from Fedora, thanks guys :]
    %patch -p1 < $pkgfiles/gnome-terminal-notify-open-title-transparency.patch
    %patch -p1 < $pkgfiles/0001-build-Don-t-treat-warnings-as-errors.patch
    # Solus
    %patch -p1 < $pkgfiles/0001-Restore-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Default-to-the-dark-theme.patch
    %reconfigure --with-nautilus-extension \
               --disable-search-provider \
               --disable-static \
               --disable-migration \
               --enable-distro-packaging
build      : |
    %make
install    : |
    %make_install
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
